"""Add indexes

Revision ID: 63a13fc870a3
Revises: fb1b3b1247a1
Create Date: 2023-02-04 15:23:47.195860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "63a13fc870a3"
down_revision = "fb1b3b1247a1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "kindcreatedpubkeyidx", "events", ["created_at", "kind", "pubkey"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("kindcreatedpubkeyidx", table_name="events")
    # ### end Alembic commands ###
